from cmu_112_graphics import *
from Node import *
from Notes import *
from Slider import *
from Player import *
from Map import *

def appStarted(app):
    ##app.map will be a list of notes generated by the map class
    app.map = Map(app, 20, 2, 1)
    app.notesMap = app.map.notesMap
    app.player = Player()
    app.time = 0
    app.x0 = 0
    app.x1 = 0
    app.side = True


def timerFired(app):
    app.time += 1
    app.pressed = False
    #toggleSide(app)
    for note in app.notesMap:
        #Updates the position of each note
        note.updateNotePos(app.time)
        extraTime = 0
        time = app.time
        if type(note) == Slider:
            extraTime = note.noteLength
            time = time - extraTime//2
        if abs(time - note.scoreTime) < 6 + extraTime:
            #Scores the note if the time == the note's game time
            score = note.scoreNote(app.player.getInputs(), app.time)
            print(score)
            app.player.updateScore(score)
    print(app.player.getInputs())
    #Testing for key held down
    #print(app.player.inputs) #prints out key value  
    #app.player.setDefaultInput()

#Helper function for later in case I can get multiple inputs working
def toggleSide(app):
    if app.side:
        app.side = False
    else:
        app.side = True        

def keyPressed(app, event):
    app.player.holdKey(event)

def keyReleased(app, event):
    app.player.releaseKey(event)

def redrawAll(app, canvas):
    app.map.drawGame(canvas)
    app.player.drawScore(canvas)

runApp(width=500, height=500)
