from cmu_112_graphics import *
from Node import *
from Notes import *
from Slider import *
from Player import *
from Map import *

def appStarted(app):
    ##app.map will be a list of notes generated by the map class
    app.map = Map(app, 20, 2, 1)
    app.notesMap = app.map.notesMap
    app.player = Player()
    app.time = 0


def timerFired(app):
    app.time += 1
    #toggleSide(app)
    for note in app.notesMap:
        #Updates the position of each note
        note.updateNotePos(app.time)
        extraTime = 0
        time = app.time
        score = 0
        if type(note) == Slider:
            extraTime = note.noteLength
            time = time - extraTime//2
        elif type(note) == Down and abs(time - note.scoreTime) < 6:
            score = note.scoreNote(app.player.getInputs(), app.player.oldInputs)
        elif abs(time - note.scoreTime) < 2:
            score = note.scoreNote(app.player.getInputs(), app.time)
        app.player.updateScore(score)
    app.player.updateOldInputs(app.player.inputs)
    #print(app.player.oldInputs)
    #print(app.player.getInputs())

def keyPressed(app, event):
    app.player.holdKey(event)



def keyReleased(app, event):
    app.player.releaseKey(event)

def redrawAll(app, canvas):
    app.map.drawGame(canvas)
    app.player.drawScore(canvas)
    app.player.drawInputs(canvas, app.height, app.map.lBorder, app.map.cellWidth)

runApp(width=500, height=500)
